import { Poppins } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "../globals.css";
import Sidebar from "@/components/layouts/Sidebar";

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MemberRootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} `}>
        <main>
          <div className="border-t">
            <div className="bg-background">
              <div className="flex flex-row">
                <div className="hidden lg:block w-[18%] ">
                  <Sidebar />
                </div>
                <div className="col-span-3 overflow-auto w-[82%]">
                  <div className="px-6 py-6 lg:px-8 bg-[#F5F5FB]">
                    {children}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </main>
        <ToastContainer />
      </body>
    </html>
  );
}
